In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr), arr.dtype,arr.shape)
arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2,type(arr2), arr2.dtype, arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (5,)


In [7]:
#2d list
arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D, arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
