In [2]:
import numpy as np

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[24, 25, 86, 28],
       [56, 73, 62, 42],
       [18, 68, 68, 90],
       [42, 80, 83, 96],
       [66, 98, 54, 62],
       [24, 92, 95, 83]], dtype=int32)

In [4]:
a = np.random.randint(1,100,15)
a

array([16, 21,  5, 55, 40, 94, 90, 68, 92, 66, 63, 68, 46, 62, 36],
      dtype=int32)

In [5]:
np.append(a,200)

array([ 16,  21,   5,  55,  40,  94,  90,  68,  92,  66,  63,  68,  46,
        62,  36, 200])

In [7]:
np.append(b,np.ones((b.shape[0],1)), axis = 1)

array([[24., 25., 86., 28.,  1.],
       [56., 73., 62., 42.,  1.],
       [18., 68., 68., 90.,  1.],
       [42., 80., 83., 96.,  1.],
       [66., 98., 54., 62.,  1.],
       [24., 92., 95., 83.,  1.]])