In [1]:
#multi dim array
import numpy as np

In [13]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_columns = np.sum(arr2D, axis=0)
print(sum_of_columns)
sum_of_rows = np.sum(arr2D, axis=1)
print(sum_of_rows)
print(arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [19]:
#3D array
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])   #2X3X2
print(arr3D,arr3D.shape, arr3D.size)
#indexing
print(arr3D[1,1,0])
print(arr3D[0,1,1])
#slicing
print(arr3D[:, 0, :]) # first row from both layers
print(arr3D[:, :, 0]) # first column from both layers
arr3D[:, 0, :] =99 
print(arr3D[:, 0, :])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2) 12
9
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[99 99]
 [99 99]]
