In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr), arr.dtype,arr.shape)
arr2 = np.array([1,2,3,4,5, "prime"])
print(arr2,type(arr2), arr2.dtype, arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (5,)


In [4]:
#2d list
arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D, arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [16]:
arr1 = np.zeros((2,3), dtype = "int64") #prefill
print(arr1,arr1.shape)
arr2 = np.ones((5, )) #prefill
print(arr2,arr2.shape)
arr3 = np.full((3,4), 100) #prefill with val
print(arr3,arr3.shape)
arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)
arr5 = np.arange(0,11,2) #range elements
print(arr5, arr5.shape)
arr6 = np.linspace(1,100,4) #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [17]:
#typecasting
float_arr = arr.astype(np.float64)