In [2]:
import numpy as np

In [3]:
#Mathematical fnx

#aggregation

arr = np.array( [1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [4]:
#power function
arr = np.array( [1, 2, 3, 4, 5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [5]:
#log
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [6]:
#rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

3.0
4.0
3.0
3.0


In [7]:
arr = np.array([1, 2, -8, 3, 4, -5, 2, -5])

print(np.unique(arr))
print(np.sort(arr))

print(np.abs(arr))

[-8 -5  1  2  3  4]
[-8 -5 -5  1  2  2  3  4]
[1 2 8 3 4 5 2 5]


In [8]:
a = np.random.randint(1,100,15)
a

array([50, 99, 73, 74,  5, 62, 70, 47, 80, 56, 92, 96, 96, 10, 53],
      dtype=int32)

In [9]:
# find all indices with value greater than 50

In [10]:
np.where(a>50)

(array([ 1,  2,  3,  5,  6,  8,  9, 10, 11, 12, 14]),)

In [11]:
# replace these values with 0

In [12]:
np.where(a>50,0,a)

array([50,  0,  0,  0,  5,  0,  0, 47,  0,  0,  0,  0,  0, 10,  0],
      dtype=int32)

In [13]:
np.cumsum(a)

array([ 50, 149, 222, 296, 301, 363, 433, 480, 560, 616, 708, 804, 900,
       910, 963])

In [14]:
np.cumprod(a)

array([                  50,                 4950,               361350,
                   26739900,            133699500,           8289369000,
               580255830000,       27272024010000,     2181761920800000,
         122178667564800000, -7206306657747951616,  9170835657159606272,
       -5043492450736275456,  4905307713765900288,  1726891797658992640])

In [17]:
np.percentile(a,100)
np.percentile(a,50)

np.float64(70.0)

In [18]:
np.histogram(a,bins = [0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 0, 0, 1, 3, 1, 3, 1, 4]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [19]:
   a

array([50, 99, 73, 74,  5, 62, 70, 47, 80, 56, 92, 96, 96, 10, 53],
      dtype=int32)

In [20]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [21]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [22]:
items = [10,20,30,40,50,60,70,80,90,100]

In [27]:
np.isin(a,items)

array([ True, False, False, False, False, False,  True, False,  True,
       False, False, False, False,  True, False])

In [26]:
a[np.isin(a,items)]

array([50, 70, 80, 10], dtype=int32)

In [28]:
np.flip(a)

array([53, 10, 96, 96, 92, 56, 80, 47, 70, 62,  5, 74, 73, 99, 50],
      dtype=int32)

In [29]:
b = np.array()

NameError: name 'b' is not defined