In [2]:
import numpy as np

In [3]:
#Mathematical fnx

#aggregation

arr = np.array( [1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [4]:
#power function
arr = np.array( [1, 2, 3, 4, 5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [5]:
#log
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [6]:
#rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

3.0
4.0
3.0
3.0


In [7]:
arr = np.array([1, 2, -8, 3, 4, -5, 2, -5])

print(np.unique(arr))
print(np.sort(arr))

print(np.abs(arr))

[-8 -5  1  2  3  4]
[-8 -5 -5  1  2  2  3  4]
[1 2 8 3 4 5 2 5]


In [8]:
a = np.random.randint(1,100,15)
a

array([21,  4, 29, 24, 16, 80,  7, 20, 29, 59, 20, 68, 16, 26, 26],
      dtype=int32)

In [9]:
# find all indices with value greater than 50

In [10]:
np.where(a>50)

(array([ 5,  9, 11]),)

In [11]:
# replace these values with 0

In [12]:
np.where(a>50,0,a)

array([21,  4, 29, 24, 16,  0,  7, 20, 29,  0, 20,  0, 16, 26, 26],
      dtype=int32)

In [13]:
np.cumsum(a)

array([ 21,  25,  54,  78,  94, 174, 181, 201, 230, 289, 309, 377, 393,
       419, 445])

In [14]:
np.cumprod(a)

array([                  21,                   84,                 2436,
                      58464,               935424,             74833920,
                  523837440,          10476748800,         303825715200,
             17925717196800,      358514343936000,    24378975387648000,
         390063606202368000, -8305090312447983616,  5428580760867045376])

In [15]:
np.percentile(a,100)
np.percentile(a,50)

np.float64(24.0)

In [16]:
np.histogram(a,bins = [0,10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 8, 0, 0, 1, 1, 0, 1, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [20]:
a

array([21,  4, 29, 24, 16, 80,  7, 20, 29, 59, 20, 68, 16, 26, 26],
      dtype=int32)

In [21]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [22]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [23]:
items = [10,20,30,40,50,60,70,80,90,100]

In [24]:
np.isin(a,items)

array([False, False, False, False, False,  True, False,  True, False,
       False,  True, False, False, False, False])

In [25]:
a[np.isin(a,items)]

array([80, 20, 20], dtype=int32)

In [26]:
np.flip(a)

array([26, 26, 16, 68, 20, 59, 29, 20,  7, 80, 16, 24, 29,  4, 21],
      dtype=int32)

In [27]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[28,  3, 50, 15],
       [ 8, 67, 22, 58],
       [84, 31, 51, 72],
       [44, 75, 45, 61],
       [14, 22, 70, 81],
       [56,  8,  9, 30]], dtype=int32)

In [28]:
np.flip(b)

array([[30,  9,  8, 56],
       [81, 70, 22, 14],
       [61, 45, 75, 44],
       [72, 51, 31, 84],
       [58, 22, 67,  8],
       [15, 50,  3, 28]], dtype=int32)

In [29]:
np.flip(b,axis = 0)

array([[56,  8,  9, 30],
       [14, 22, 70, 81],
       [44, 75, 45, 61],
       [84, 31, 51, 72],
       [ 8, 67, 22, 58],
       [28,  3, 50, 15]], dtype=int32)

In [30]:
np.flip(b,axis = 1)

array([[15, 50,  3, 28],
       [58, 22, 67,  8],
       [72, 51, 31, 84],
       [61, 45, 75, 44],
       [81, 70, 22, 14],
       [30,  9,  8, 56]], dtype=int32)

In [31]:
a

array([21,  4, 29, 24, 16, 80,  7, 20, 29, 59, 20, 68, 16, 26, 26],
      dtype=int32)

In [32]:
np.put(a,[0,1],[110,530])

In [33]:
a

array([110, 530,  29,  24,  16,  80,   7,  20,  29,  59,  20,  68,  16,
        26,  26], dtype=int32)

In [35]:
#delete
np.delete(a,0)

array([530,  29,  24,  16,  80,   7,  20,  29,  59,  20,  68,  16,  26,
        26], dtype=int32)

In [36]:
np.clip(a,a_min=25,a_max = 75)

array([75, 75, 29, 25, 25, 75, 25, 25, 29, 59, 25, 68, 25, 26, 26],
      dtype=int32)