In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)
reshape = arr.reshape((3,2))
print(reshape, reshape.shape)
flattened = arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)
