In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])

In [3]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
np.intersect1d(a,b)

array([3, 4, 5])

In [5]:
np.setdiff1d(a,b)

array([1, 2])

In [6]:
np.setxor1d(a,b)

array([1, 2, 6, 7])

In [8]:
np.in1d(a,1)

C:\Users\madha\AppData\Local\Temp\ipykernel_12824\1506200059.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a,1)


array([ True, False, False, False, False])