In [1]:
import numpy as np

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[10, 78, 81, 72],
       [58, 25, 14, 45],
       [67, 22, 43, 58],
       [71, 70,  3, 94],
       [98, 35, 46, 92],
       [82, 88, 12, 51]], dtype=int32)

In [4]:
a = np.random.randint(1,100,15)
a

array([63,  6, 55, 36, 44, 47, 76, 74, 61, 20, 29, 62, 46, 36, 88],
      dtype=int32)

In [5]:
np.sort(a)

array([ 6, 20, 29, 36, 36, 44, 46, 47, 55, 61, 62, 63, 74, 76, 88],
      dtype=int32)

In [9]:
np.sort(a)[::-1]# for decending order

array([88, 76, 74, 63, 62, 61, 55, 47, 46, 44, 36, 36, 29, 20,  6],
      dtype=int32)

In [6]:
np.sort(b)# row wise sorting

array([[10, 72, 78, 81],
       [14, 25, 45, 58],
       [22, 43, 58, 67],
       [ 3, 70, 71, 94],
       [35, 46, 92, 98],
       [12, 51, 82, 88]], dtype=int32)

In [8]:
np.sort(b, axis = 0)# column wise sorting

array([[10, 22,  3, 45],
       [58, 25, 12, 51],
       [67, 35, 14, 58],
       [71, 70, 43, 72],
       [82, 78, 46, 92],
       [98, 88, 81, 94]], dtype=int32)